development:
  adapter: postgresql
  encoding: unicode
  database: statofun_development
  host: localhost
  pool: 5
  username: statofun
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: statofun_production
  pool: 5
  username: statofun
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: statofun_test
  pool: 5
  username: statofun
  password:
