development:
  adapter: postgresql
  encoding: unicode
  database: statofun_development
  host: localhost
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: statofun_production
  pool: 5
  username: statofun
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: statofun_test
  pool: 5
  template: template0